// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ButtonIcon: typeof import('./src/components/atoms/button-icon.vue')['default']
    Chat: typeof import('./src/components/atoms/icons/chat.vue')['default']
    Class: typeof import('./src/components/atoms/icons/class.vue')['default']
    Contract: typeof import('./src/components/atoms/icons/contract.vue')['default']
    Dropdown: typeof import('./src/components/atoms/icons/dropdown.vue')['default']
    House: typeof import('./src/components/atoms/icons/house.vue')['default']
    Idea: typeof import('./src/components/atoms/icons/idea.vue')['default']
    Logo: typeof import('./src/components/atoms/icons/logo.vue')['default']
    Moon: typeof import('./src/components/atoms/icons/moon.vue')['default']
    Navbar: typeof import('./src/components/organisms/navbar.vue')['default']
    Notification: typeof import('./src/components/atoms/icons/notification.vue')['default']
    Portal: typeof import('./src/components/templates/portal.vue')['default']
    Sun: typeof import('./src/components/atoms/icons/sun.vue')['default']
    Toggle: typeof import('./src/components/atoms/toggle.vue')['default']
  }
}

export { }
